apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: danify-prod
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.discord: ""
    notifications.argoproj.io/subscribe.on-sync-failed.discord: ""
    notifications.argoproj.io/subscribe.on-health-degraded.discord: ""
spec:
  project: default
  source:
    repoURL: https://github.com/danify-cz/danify-gitops.git
    path: environments/prod
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: danify
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m
        factor: 2
