---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
spec:
  encryptedData:
    discord-webhook-url: AgBAGA+Seq7TM5KZ6QGIgatgeAe62fiiY2pcB4IWLJcTeCAjT6Hp7ECwO9Z9P1MtEuaU+1Dfj1UaV6zbbu0dohAt99DaTgMliQYagG++aY66kwdOD8qyw4JT2vTHvSZCu9s2WLUJFrJ6uDLJld1vuvTCrAtT42h27OHTlaWiPAmHZ659m3pLeOsJI3ih7HcUuXrRWpRc+iGhjp3Pdjl6jpKS5AM11vp75DwmkTNbP5hFoiPUwbpFFgyhioKXbnZNbUj9UZtLfD8dwWhXB101dT84ixJwliQaDVRuHFxXKd5f+2ATRHsvpcnLgX0YBbWPdzVMKu2vuPC/5R73b7a4jLBhdRuJVN6k1t5XrjUPMBopEUfBRbLhhJI+g6/WZn4j8s7+UfvtkMexLa8Tm8OenvvgAZ+CawneKvas2fVWqFEW0M9FpJ+RMU+WP2iHf5VbJePTL55yjqRynFBI96Iod5nFoXKrQjVf6BX+PXvpZ5mKVxPvVavQb6NHfgTzEhMUDicXTEln88CNDK78fUukdATQs2cu6+rQ8K62faphBQj97js9MavaogYEOLUsBN2yNRRpePgGjkNIQfRYLyI15/4wMdnXXCKEF/jPdTkHwVR9uP46NuQT1C00alVGu6ixcEfPKlSH+x27D6pLLqva07T4vwAJiLruznvGm31Z87IwmUXRH7JcxLg9ecKqoBw8IwGtJAUQH7UWpfz41uW1lmnJQ+hGRxifeO8E5tl3g2d4HoHCprPv2e70qTUKkEZlVX9yCnQRlUd6DRuUtEt7Fn/JGP3VkW0JmAIFGSB8cpwFw7ZkPXt9LwKpG32PigsQwW9sOCf+TkJoV8splNTHgtEfrLSbTF9iBJTv
  template:
    metadata:
      name: argocd-notifications-secret
      namespace: argocd
    type: Opaque
