---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
spec:
  encryptedData:
    discord-webhook-url: AgA8FpZv1BiWucNtmMaWit+ZyVc3KRZWC0lL2J+p/Z37NNQ87nhRlQGu49C55/xsh/l/+xCk/Dhdd/sBT1bbdTHtMHu8OdtqCqEvwf/oJxS4aSUZt0wIThfHsfDfdnsGqB7pQ2JU7jv+z40PiP+AC1tEBMniF/7+/rYjrV8b2T7CTsSX0hdiBPQujn31S1VCuu7d9NuJnKy1oTEyHlwXsysvuhmOOPZOID0kAQMrAgs44s28vyZGoU5y2Px0iWdLAmYAELEIRMsi9BTWixUo/yt+0BN6iNCwAtwRhpfk0yaEwNTMSHKW4xKzZMoE+n9N6QoN/2VwOG68Cwav0IkUVjEMewnUsPKxi/iEY2CJxy0Gtr9fUJF/PzonVfwGZadthlJlTnH3bdEMrpYNjhRxrP9PbT/W49be3D6JaNC6lkgUU3e3Nvjp5dsKJCVXTWfgU+7NRVWU4ay7v14x3gusC6f967j8J5bJTOw+xF6Gm586t92jS2nEAQnSBMqB8R3tK/M4pOIh7ogTc717ItKffFBRhdqV+u3/ZSPiuQHBWgZZtl+oT4R6mzSS/7u4NTc2kdpCPlylF4dfBl02Bg3qpJ2/59o8nikqRbDkphxizF0UEM1VJnORrMEfdXbVzeIJSMISY39AOakX1+35ZdSPXYINAVL2x2Ml5O8kp1yb4oogeXRH0UUfZzMh0LzrH+xUGzGvaN6j3eg+7M9ArelSWX8eafRGVr4T/BRq50UrTxs4u2omi9jf751qvAMcBH1M1t9IaBxRTuYH1HkL6tnI9HmOXqsj6/pXxfeP7H0/lu5MbjS2t8DZgD3qa2yR1oSxzctn13JEEIM4UcAOGRe7jjTm9Ul0z5B8wFe2
  template:
    metadata:
      name: argocd-notifications-secret
      namespace: argocd
    type: Opaque
