# Template for GHCR pull secret
# This needs to be encrypted with kubeseal before applying
#
# To create the actual secret:
# 1. Generate GitHub Personal Access Token with read:packages scope
# 2. Base64 encode: echo -n "USERNAME:TOKEN" | base64
# 3. Replace REPLACE_WITH_BASE64_ENCODED_CREDENTIALS in env-specific ghcr-secret.yaml
#
# Or use kubeseal:
# kubectl create secret docker-registry ghcr-pull-secret \
#   --docker-server=ghcr.io \
#   --docker-username=YOUR_GITHUB_USERNAME \
#   --docker-password=YOUR_GITHUB_TOKEN \
#   --namespace=danify \
#   --dry-run=client -o yaml | \
#   kubeseal --format yaml > environments/ENV/ghcr-secret.sealed.yaml

apiVersion: v1
kind: Secret
metadata:
  name: ghcr-pull-secret
  namespace: danify
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "ghcr.io": {
          "auth": "REPLACE_WITH_BASE64_ENCODED_CREDENTIALS"
        }
      }
    }
