apiVersion: v1
kind: ConfigMap
metadata:
  name: danify-fe-config
data:
  config.json: |
    {
      "apiUrl": "https://api.dev.danify.cz:9443",
      "version": "dev-8e2ae4f",
      "sentryDsn": "https://e57eb7f6466a2f2b6f586dd3d3ad6c2a@o4511461083447296.ingest.de.sentry.io/4511461098389584",
      "sentryEnvironment": "dev",
      "turnstileSiteKey": "0x4AAAAAADot1DPgtA95B5DR"
    }
